### ISSUE TITLE
Errori nelle slide 

### ISSUE THREAD

**Issue by Correndo-Marco** [profmancusoa/RETI#22]
In RETI_3 in linux_cli/linux_cli_slides.md ci sono errori:
riga 279, correggere piatatforma a piattaforma
riga 280, correggere vaso a vasto
riga 309, correggere da screenshoot a screenshot e togliere un su
riga 671, correggere da screenshoots a screenshots e togliere un su
riga 1009, correggere da screenshoot a screenshot e togliere un su
riga 1245, correggere da screenshoots a screenshots e togliere un su
riga 1969, correggere da screenshoots a screenshots e togliere un su
riga 2682, correggere da screenshoots a screenshot e togliere un su
riga 2838, correggere da screenshoots a screenshot e togliere un su
riga 2988, correggere da screenshoots a screenshots e togliere un su

**Comment by profmancusoa** [comment]
pare che questi errori siano già corretti
